import type { Metadata } from 'next';
import './globals.css';
import QueryProviders from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <QueryProviders>
          <main className="flex flex-col relative w-[600px] min-w-custom max-w-custom min-h-screen m-auto bg-white shadow-xl">
            {children}
          </main>
          {modal}
          <div id="modal-root" className=""></div>
        </QueryProviders>
      </body>
    </html>
  );
}
