import type { Metadata } from 'next';
import './globals.css';
import QueryProviders from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <main className="flex flex-col relative w-[600px] min-w-custom max-w-custom min-h-screen m-auto bg-white shadow-xl">
          <QueryProviders>{children}</QueryProviders>
        </main>
      </body>
    </html>
  );
}
